version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

environment:
  GitHubKey:
    secure: unWb9ORoL3oo22K6z2U2fZ+AdBmv75laNb7jibBwQCMGv9u8Cs2GayQBGjkqfPro

image: WMF 5
deploy: off

only_commits:
  files:
    - icons/

install:
- ps: . .\tests\Install.ps1

test_script:
  - ps: $res = Invoke-Pester -Path ".\tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
  - git config --global user.email "aaron@stealthpuppy.com"
  - git config --global user.name "Aaron Parker"
  - git config --global core.autocrlf true
  - git config --global core.safecrlf false

  build_script:
  - ps: . .\tests\Build.ps1
